Firehose commit c5505756471b9820a59edb8ae6da2b7d5d607a95 code generation
set /bigobj

fixes: fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj