Firehose commit 98004d3c9eba953120c21d5971b955f009962605 code generation
set /bigobj

fixes: fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj